services:
  sr_api:
    image: ghcr.io/krau/super-resolution-api:latest
    container_name: sr_api
    restart: always
    volumes:
      - ./output:/sr_api/output
      - ./temp:/sr_api/temp
    env_file:
      - .env
    network_mode: host