provider = "CPUExecutionProvider"
token = "qwqowo"
redis_url = "redis://localhost:6379"
host = "0.0.0.0"
port = 39721
max_timeout = 300
timeout = 30
max_workers = 8
mode = "master"                        # master, slave, single
master_url = "http://localhost:39721"
master_token = "qwqowo"
worker_id = "test"
worker_host = "127.0.0.1"
temp_dir = "./temp"
output_dir = "./output"
