provider = "CPUExecutionProvider"
token = "qwqowo"
redis_url = "redis://localhost:6379"
host = "0.0.0.0"
port = 39721
max_timeout = 300
timeout = 30
max_thread = 8
mode = "master"                       # master, slave, single
master_url = "http://localhost:39721"
master_token = "qwqowo"
worker_id = ""
worker_url = "http://localhost:39721"
temp_dir = "./temp"
output_dir = "./output"
log_level = "DEBUG"